import {it,expect} from 'vitest';
import {derive,calculateSpellDamage,calculateAccuracy} from '../../game/calculation';
import {newCampaign,makeBattle,learnAbility,trainingFor,equipSupport,classLevel,reward,encodeCampaign,parseCampaign,act,damage,targets,itemStock} from '../../game/domain';
it('OV v1.10a spell coefficients use INT/MND versus RES/MND and half DEF',()=>{const a=derive(2,1,{weapon:0,armor:0}),t=derive(0,1,{weapon:0,armor:0});expect(a.spellPower).toBeCloseTo(a.stats.int*1.2+a.stats.mnd*.6);expect(t.resilience).toBe(t.stats.res+t.stats.mnd*.5);const normal=calculateSpellDamage(a,t,17);expect(calculateSpellDamage(a,{...t,resilience:t.resilience+10},17).final).toBeLessThan(normal.final);expect(calculateSpellDamage(a,t,17,0).final-normal.final).toBeGreaterThanOrEqual(4);});
it('accuracy responds to AGI and AVD, respects direction floors, and caps at 100',()=>{const a=derive(0,1,{weapon:0,armor:0}),t=derive(0,1,{weapon:0,armor:0});const base=calculateAccuracy(a,t,'front');expect(calculateAccuracy({...a,stats:{...a.stats,agi:a.stats.agi+3}},t,'front').chance).toBeGreaterThan(base.chance);expect(calculateAccuracy(a,{...t,stats:{...t.stats,avd:t.stats.avd+10}},'front').chance).toBeLessThan(base.chance);expect(calculateAccuracy(a,{...t,stats:{...t.stats,avd:1000}},'back').chance).toBe(60);});
it('learned abilities, equipped support and shared class levels survive save and revisiting stage one',()=>{const c=newCampaign();expect(learnAbility(c,2,'moon-bolt')).toBe(true);expect(trainingFor(c,2).sp).toBe(0);equipSupport(c,2,'fleet-foot');const before=makeBattle(0,c).units[2];expect(before.abilityId).toBe('moon-bolt');expect(before.move).toBe(4);reward(c,0);expect(classLevel(c,2)).toBe(2);expect(makeBattle(0,c).units[2].derived.stats.int).toBeGreaterThan(before.derived.stats.int);expect(parseCampaign(encodeCampaign(c))).toEqual(c);});
it('a newly shipped class casts a registry-based area guard on allies only',()=>{const c=newCampaign();c.party=[4,0,1];const b=makeBattle(0,c),u=b.units[0];u.tp=20;expect(u.classId).toBe('sentinel');expect(act(b,u,b.units[1],'skill')).toBe(true);expect(b.units[1].guard).toBe(true);expect(b.units.filter(v=>v.team==='enemy').every(v=>!v.guard)).toBe(true);});
it('rejects old incomplete roster saves without adding default equipment',()=>{const disk=JSON.parse(encodeCampaign(newCampaign()));delete disk.equipment.lena;delete disk.equipment.iris;const raw=JSON.stringify(disk);expect(parseCampaign(raw)).toBeNull();expect(JSON.stringify(disk)).toBe(raw);});

it('MP and TP items preview exact capped restoration, spend one charge, and grant no damage TP',()=>{for(const [item,resource,maximum] of [['aether-draught','mp',24],['valor-draught','tp',100]] as const){const b=makeBattle(0,newCampaign()),u=b.units[0];u.itemId=item;u[resource]=maximum-3;const hp=u.hp;expect(damage(b,u,u,'item')).toBe(3);expect(targets(b,u,'item')).toContain(u);expect(act(b,u,u,'item')).toBe(true);expect(u[resource]).toBe(maximum);expect(u.hp).toBe(hp);expect(itemStock(b,u)).toBe(0);expect(targets(b,u,'item')).toEqual([]);if(resource==='mp')expect(u.tp).toBe(0);}});
it('invalid learned/equipped ability references cannot enter a saved campaign',()=>{const disk=JSON.parse(encodeCampaign(newCampaign()));disk.training={erin:{sp:8,learned:['unknown'],abilityId:'unknown',supportId:'weapon-study'}};expect(parseCampaign(JSON.stringify(disk))).toBeNull();});
it('all five equipment slots feed status, hit damage and stable-ID save restoration',()=>{const c=newCampaign(),before=makeBattle(0,c);c.gear[0]={weapon:1,armor:1,offhand:1,armguard:1,accessory:1};const b=makeBattle(0,c),u=b.units[0],t=b.units[3];expect(u.derived.stats.str).toBe(before.units[0].derived.stats.str+3);expect(u.derived.statBreakdown.str).toEqual({base:10,class:15,gear:3});expect(u.derived.stats.vit).toBe(before.units[0].derived.stats.vit+2);expect(u.derived.stats.dex).toBe(before.units[0].derived.stats.dex+2);expect(u.def).toBe(before.units[0].def+7);t.x=u.x+1;t.y=u.y;t.facing='SE';const expected=damage(b,u,t,'attack'),hp=t.hp;expect(act(b,u,t,'attack')).toBe(true);expect(t.hp).toBe(Math.max(0,hp-expected));expect(parseCampaign(encodeCampaign(c))).toEqual(c);const bad=JSON.parse(encodeCampaign(c));bad.equipment.erin.accessoryId='unknown-jewel';expect(parseCampaign(JSON.stringify(bad))).toBeNull();});
