import {test,expect,type Page} from '@playwright/test';
test.use({viewport:{width:1024,height:768},deviceScaleFactor:2});
const diag=(p:Page):Promise<any>=>p.evaluate('window.tacticsDiagnostics()');
async function choose(p:Page,id:string){for(let i=0;i<100;i++){if(await p.evaluate(()=> (document.activeElement as HTMLElement)?.dataset.id)===id){await p.keyboard.press('Enter');return;}await p.keyboard.press('ArrowDown');}throw Error('Unreachable '+id);}
async function boot(p:Page){await p.goto('/game/');await p.waitForFunction('window.tacticsDiagnostics');}
async function battle(p:Page){await boot(p);for(const id of ['new','stage-0','party','deploy','talk-0','talk-0'])await choose(p,id);}
async function mock(p:Page){await p.addInitScript(`window.padButtons=[];window.padConnected=true;Object.defineProperty(navigator,'getGamepads',{value:()=>window.padConnected?[{connected:true,index:0,mapping:'standard',axes:[0,0,0,0],buttons:Array.from({length:16},(_,i)=>({pressed:window.padButtons.includes(i),value:window.padButtons.includes(i)?1:0}))}]:[]});`);}
async function pad(p:Page,buttons:number[]){await p.evaluate(v=>{(window as any).padButtons=v},buttons);await p.waitForTimeout(65);await p.evaluate(()=>{(window as any).padButtons=[]});await p.waitForTimeout(65);}
test('F01 keyboard focus on target cancel returns without attacking',async({page})=>{await battle(page);await page.keyboard.press('e');await choose(page,'move');for(const k of ['ArrowRight','ArrowDown','ArrowRight','ArrowRight'])await page.keyboard.press(k);await page.keyboard.press('Enter');await expect.poll(async()=> (await diag(page)).mode).toBe('command');await choose(page,'attack');await expect(page.locator('.target-pair canvas')).toHaveCount(2);for(let i=0;i<20&&await page.evaluate(()=>(document.activeElement as HTMLElement)?.dataset.id)!=='back-command';i++)await page.keyboard.press('Tab');await expect(page.locator('[data-id=back-command]')).toBeFocused();const before=(await diag(page)).battle;await page.keyboard.press('Enter');expect((await diag(page)).mode).toBe('command');expect((await diag(page)).battle).toEqual(before);});
test('F02 controller can cancel both keyboard and button capture without a keyboard',async({page})=>{await mock(page);await boot(page);await choose(page,'settings');await choose(page,'bind-keys-0');await pad(page,[1]);await expect(page.locator('[role=dialog]')).not.toContainText('사용할 키를');await choose(page,'bind-buttons-0');const before=(await diag(page)).bindings;await pad(page,[8]);await expect(page.locator('[role=dialog]')).not.toContainText('사용할 패드 버튼');expect((await diag(page)).bindings).toEqual(before);});
test('F03 reserved Tab is not saved; a remapped Space performs only its action',async({page})=>{await battle(page);await page.keyboard.press('p');await choose(page,'settings');await choose(page,'bind-keys-0');await page.keyboard.press('Tab');expect((await diag(page)).bindings.keys.up).toBe('ArrowUp');await page.keyboard.press('Escape');await choose(page,'settings-next');await choose(page,'bind-keys-9');await page.keyboard.press('Space');await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.keyboard.press('e');const before=await diag(page);await page.keyboard.press('Space');const after=await diag(page);expect(after.top).not.toBe(before.top);expect(after.mode).toBe(before.mode);});
test('F04 held input cannot dismiss pause on refocus or controller disconnect',async({page})=>{await mock(page);await battle(page);await page.evaluate(()=>{(window as any).padButtons=[0]});await page.waitForTimeout(70);await page.evaluate(()=>dispatchEvent(new Event('blur')));expect((await diag(page)).modal).toBe('pause');await page.evaluate(()=>dispatchEvent(new Event('focus')));await page.waitForTimeout(70);expect((await diag(page)).modal).toBe('pause');await page.evaluate(()=>{(window as any).padButtons=[]});await page.waitForTimeout(70);await pad(page,[0]);expect((await diag(page)).modal).toBeNull();await page.keyboard.down('Enter');await page.evaluate(()=>{(window as any).padConnected=false});await page.waitForTimeout(70);expect((await diag(page)).modal).toBe('pause');await page.keyboard.up('Enter');});
test('F05 canceling end-turn grants no free guard',async({page})=>{await battle(page);await page.keyboard.press('e');const before=(await diag(page)).battle.units[0];await choose(page,'wait');await page.keyboard.press('Escape');expect((await diag(page)).battle.units[0]).toEqual(before);});
test('F08 editor replacement references are rendered rather than silently discarded',async({page})=>{await boot(page);const result=await page.evaluate(`(async()=>{const {Renderer}=await import('/game/render.ts');const {makeBattle,newCampaign}=await import('/game/domain.ts');const rig=(await import('/game/assets/dawn-rig.json')).default;const copy=structuredClone(rig);copy.views.Front.parts.find(p=>p.id==='armR').replacement={id:'audit-blue',name:'audit-blue.png',width:10,height:10};const cv=document.createElement('canvas');cv.width=10;cv.height=10;cv.getContext('2d').fillStyle='#00ffff';cv.getContext('2d').fillRect(0,0,10,10);const image=cv.toDataURL();const host=document.createElement('div');document.body.append(host);const r=new Renderer(host);await r.setRig(copy,'/game/assets/dawn-parts.png',{'audit-blue':image});await new Promise(q=>setTimeout(q,100));const calls=[];const ctx=r.canvas.getContext('2d'),original=ctx.drawImage.bind(ctx);ctx.drawImage=(img,...args)=>{calls.push(img.src||'tint');original(img,...args)};r.cell=100;r.actor(makeBattle(0,newCampaign()).units[0],{x:150,y:300},false,false,false);return calls.some(src=>src.startsWith('data:image/png'))})()`);expect(result).toBe(true);});
test('F09 unit labels are drawn after all opaque terrain and sprites in both projections',async({page})=>{await boot(page);const result=await page.evaluate(`(async()=>{const {Renderer}=await import('/game/render.ts');const {makeBattle,newCampaign}=await import('/game/domain.ts');const host=document.createElement('div');document.body.append(host);const r=new Renderer(host);await new Promise(q=>setTimeout(q,120));const b=makeBattle(0,newCampaign());const c=r.canvas.getContext('2d'),img=c.drawImage.bind(c),text=c.fillText.bind(c),ops=[];c.drawImage=(...a)=>{ops.push('image');img(...a)};c.fillText=(label,...a)=>{ops.push(b.units.some(u=>u.name===label)?'name':'other');text(label,...a)};const result=[];for(const top of [false,true]){ops.length=0;r.draw({command:'attack',battle:b,cursor:{x:1,y:2},selected:null,mode:'select',top,zoom:1,pan:{x:0,y:0},paused:false},1000);result.push(ops.slice(ops.indexOf('name')).includes('image'));}return result})()`);expect(result).toEqual([false,false]);});

test('Tab focus on settings during facing opens settings without ending the AT',async({page})=>{await battle(page);await page.keyboard.press('e');await choose(page,'wait');const before=(await diag(page)).battle;for(let i=0;i<20&&await page.evaluate(()=>(document.activeElement as HTMLElement)?.dataset.id)!=='settings';i++)await page.keyboard.press('Tab');await page.keyboard.press('Enter');expect((await diag(page)).modal).toBe('settings');expect((await diag(page)).battle).toEqual(before);});
